### ISSUE TITLE
Behavior of ideep::direct_copy::compute

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#10]
When `&X == &Y` in `ideep::direct_copy::compute(X, Y)`. What is the result of this computation? Is it safe to do so? Thanks. 

Context: 
https://github.com/pytorch/pytorch/blob/769397eb7714c9da1ff3a472f67f063e2da7c483/caffe2/ideep/operators/elementwise_sum_op.cc#L19

**Comment by gujinghui** [comment]
Yes. It should be safe. Will fix it in latest ideep code.

**Comment by yinghai** [comment]
> Yes. It should be safe. Will fix it in latest ideep code.

This means it's not safe now as in ideep master, right?

**Comment by gujinghui** [comment]
has been fixed in pytorch/pytorch#8364

**Comment by yinghai** [comment]
Close?
