### ISSUE TITLE
Bug in depthwise conv with group=4

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#11]
Check https://github.com/pytorch/pytorch/pull/8301 for a minimal repo. I met with a segfault on my machine and it seems to originate from the git code of MKL-DNN.

**Comment by yinghai** [comment]
@4pao @gujinghui

**Comment by yinghai** [comment]
Specific kernel in question is: `mkldnn_dump_jit_avx2_1x1_conv_kernel_f32.X.bin`

**Comment by 4pao** [comment]
Will check it.

**Comment by gujinghui** [comment]
Fixed in latest ideep and #8364

**Comment by yinghai** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/8364

**Comment by yinghai** [comment]
I think we can close this one out.
