### ISSUE TITLE
which ideep branch is meant for pytorch integration?

### ISSUE THREAD

**Issue by snadampal** [intel/ideep#112]
Hi, I see several branches in ideep with pytorch reference; for example I see `pytorch-internal` and `pytorch_dnnl`
Currently I have this [PR](https://github.com/intel/ideep/pull/109) for `pytorch-internal`, and I'm looking for getting this into PyTorch 1.13. Please let me know if this is not the correct branch and appreciate any feedback on the PR. thank you!

**Comment by snadampal** [comment]
Hi @XiaobingSuper , could you please comment on this? I'm looking for the right branch to push my PR to. thanks!

**Comment by XiaobingSuper** [comment]
[Guobing-Chen](https://github.com/Guobing-Chen),  please help comment it.

**Comment by Guobing-Chen** [comment]
pytorch-internal and pytorch_dnnl are both deprecated now. Instead, ideep_dev and ideep_pytorch are the two branches that we will mainly use for pytorch developement. ideep_dev as the main dev branch, and ideep_pytorch is the branch for public pytorch. The major difference of these two branches should be only about llga/oneDNN version and potential related code change.

All new PRs should go land into ideep_dev firstly (except specific llga/oneDNN version update that need to go into ideep_pytorch directly), and related commits will then be cherry-picked to ideep_pytorch.

Internal pytorch will use ideep_dev branch as the main branch while public pytorch will use ideep_pytorch branch.

Currently, public pytorch still use pytorch_dnnl branch and we are under submitting PR to pytorch to change to use ideep_pytorch, which should happen after pytorch 1.13

**Comment by snadampal** [comment]
Thanks @Guobing-Chen .If I understand correctly, post PyTorch 1.13, all PRs should be raised against` ideep_dev`.
But how about the PRs targeted for PyTorch 1.13 release? is the `pytorch-internal` okay?

btw, what is the oneDNN version you are targeting for PyTorch 1.13 release?

**Comment by Guobing-Chen** [comment]
We don't have plan to update ideep any more in pytorch 1.13 window as the 1.13 due-date is very close. I'd suggest you to submit PR to ideep_dev and targeting pytorch 1.14.

**Comment by sanchitintel** [comment]
Hi @Guobing-Chen, I'd be updating LLGA commit to alpha patch release 0.5.2 before Sep 30 (for PyTorch 1.13).
It has been validated internally. Which branch should I submit the PR to?
Thanks!

**Comment by snadampal** [comment]
Hi @Guobing-Chen , @XiaobingSuper , can you please let me know if ideep_dev is the branch for PyTorch2.0.  currently PyTorch master is not pointing to the ideep_dev, so, I'm testing all my changes with the ideep version that is on pyTorch master.  i'm wondering how one can test ideep_dev latest commit with PyTorch. Please let me know. Thank you!

**Comment by nSircombe** [comment]
Hi,

Related to this Issue - I was wondering if you'd be able to provide some clarity on how the integration of oneDNN into iDeep and iDeep into PyTorch is handled?

At present the iDeep submodule in PyTorch leads to this commit - https://github.com/intel/ideep/tree/e7925bc7c260e6c4481ccb53b7d29c59a901a05d.

This has oneDNN as another submodule, currently pointing to this commit - https://github.com/oneapi-src/oneDNN/tree/6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e

...but that doesn't appear to be a commit from the history of `master`, or any of the oneDNN release branches, it all appears to be on the branch https://github.com/oneapi-src/oneDNN/compare/dev-graph-beta-3-no-submod.

Also, until this commit - https://github.com/oneapi-src/oneDNN/commit/59cb38b7228d88bdb48abf84ce921d552fdc90e5 - iDeep was using a oneDNN commit that imported oneDNN as _another_ submodule under third_party/oneDNN, but this now appears to be another copy of oneDNN. This copy of oneDNN has been (it appears) patched up to v2.7.3 (https://github.com/oneapi-src/oneDNN/commit/6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e) but it is _not_ the 2.7.3 release tag (https://github.com/oneapi-src/oneDNN/tree/v2.7.3).

So this would mean that PyTorch isn't actually building with the released version of oneDNN?

Could you explain the rationale here, and your plans for oneDNN+iDeep integration going forwards? At best the current setup is quite confusing, at worst it's misleading, so I'm curious to know how it's arrived at this configuration.

**Comment by snadampal** [comment]
PyTorch 2.0 release was out, hence closing this.
