### ISSUE TITLE
No support to zero-dim tensors

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#12]
Hi folks, I notice that the following code will throw error 
```
ideep::tensor::resize(dims, itensor::data_type::f32);
```
if dims contains zero dimension. For example, `(0, 2)`. This is a legit tensor shape which will emerge from rcnn use case. In fact, old `MKL-ML` operators support such shapes. I don't know whether this is a regression of IDEEP or MKL-DNN. Please help us take a look. Thanks. 

You can use this tiny test case to reproduce the issue: 
https://github.com/pytorch/pytorch/pull/8459

@4pao @gujinghui

**Comment by mingxiaoh** [comment]
@yinghai can we close this issue now?

**Comment by yinghai** [comment]
I think MKLDNN added support to 0-dim tensor. Closing.
