### ISSUE TITLE
Expose `__version__` in python module

### ISSUE THREAD

**Issue by kmaehashi** [intel/ideep#13]
It is nice if version of iDeep4py module can be accessed from code, e.g.,

```py
>>> import ideep4py
>>> print(ideep4py.__version__)
2.0.0
```

So that we can embed version information in `chainer.print_runtime_info()`. It helps when we support users having difficulties with installation.
https://docs.chainer.org/en/latest/performance.html#use-the-latest-version

**Comment by 4pao** [comment]
@kmaehashi Sorry for the late response, we will provide it.

**Comment by mingxiaoh** [comment]
@kmaehashi provided in the latest ideep source code already. As for the PYPI, we plan to include the change in ideep4py 2.0.0.post1 in these two days.

**Comment by kmaehashi** [comment]
Thank you!

**Comment by mingxiaoh** [comment]
@kmaehashi  
ideep4py2.0.0.post1 has been uploaded to PYPI to support `__version__`  inquiry in python module.
pip install ideep4py==2.0.0.post1
