### ISSUE TITLE
Allow user to tune LRU size

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#14]
`1024` seems to be a pretty arbitrary number for the LRU size. Is there any way that we can change it? Even in compile time is fine. 
 
Code:
https://github.com/intel/ideep/blob/a861d8c2b2cceddb4d17b924b75bc1ce0a20eec0/include/ideep/lru_cache.hpp#L293

**Comment by 4pao** [comment]
Yes, its arbitrary. What's your scenario and suggestion?

**Comment by yinghai** [comment]
Caching excessive primitives and their buffers will cause memory bloat. And I believe this cache is per-thread, right? @gujinghui and @jgong should know about the use case more, say rcnn.

**Comment by 4pao** [comment]
I see. I'll talk to them go gather more information. Meanwhile, I think the problem might be per-operator cache will accumulate same amount of ops, that's a point we can immediately optimize.

**Comment by jgong5** [comment]
@yinghai How about we allow the control of these sizes via some environment variables, just like OMP env flags?

**Comment by yinghai** [comment]
Hi folks, I think removing per-op caching and having environment variable are both good solutions.

**Comment by mingxiaoh** [comment]
@yinghai can I close this issue now?

**Comment by jgong5** [comment]
@mingxiaoh I don't think we have implemented a solution for this issue. We may close after that.

**Comment by gujinghui** [comment]
Done in https://github.com/intel/ideep/commit/f088c56ee78bab675d922c1892018e3e93bb9eef
