### ISSUE TITLE
Behavior of Spatial BN op

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#15]
The 5th output of spatial bn (saved_variance) seems to be reciprocal of that of normal CPU spatial BN 
https://github.com/pytorch/pytorch/blob/cb98c5020a3400425a5c36ba0ddffcd6ccdb8b84/caffe2/python/ideep/spatial_bn_op_test.py#L91-L93

Any reason why?

**Comment by 4pao** [comment]
Oh, that's because MKL-DNN both variable compacted as "weights". It returns both variable as a single one. We saved a copy by reference second one to the first bottom half.

**Comment by yinghai** [comment]
Hi @4pao, thanks for the explanation. Could you point me the code where ideep does this? Thanks. 

Can we conform to the conventional one? The copy saved here doesn't seem to be significant, while change of behavior is a surprise.

**Comment by 4pao** [comment]
OK, I'll make it old one.
