### ISSUE TITLE
Is a Windows build functionnal?

### ISSUE THREAD

**Issue by vincentleon** [intel/ideep#16]
Hi ! 
I'd like to know if a windows build is functional at the moment (since it's not part of the recommended platforms). 
I tried compiling and installing it by following the readme instructions, but I'm stuck when installing the package with `cd ../python && py -3 setup.py install`. 
Intel MKL is correctly found but I'm getting LINK errors such as `gemm_convolution.obj : error LNK2019: unresolved external symbol _cblas_sgemm`. 

I attached the full trace, so you can check MKL is found, as well as the different unresolved symbols. 
[trace.txt](https://github.com/intel/ideep/files/2209087/trace.txt)

**Comment by 4pao** [comment]
Oh, I'm sorry, not yet. We are actual in the middle of enabling windows compilation. 😊

**Comment by vincentleon** [comment]
Ok thanks ! Looking forward to it then :) 
I guess I can close the issue then.
