### ISSUE TITLE
OneDNN3.x support timelines

### ISSUE THREAD

**Issue by snadampal** [intel/ideep#193]
Hi, could someone please provide details on (i) timelines for OneDNN3.x support in ideep and (ii) is the ideep_dev_3.0 the development branch for the same?
Thank you!

**Comment by snadampal** [comment]
can someone please share some details about onednn3.x support plan for PyTorch?

**Comment by snadampal** [comment]
Hi @CaoZhongZ , can you please publish the oneDNN version planned for the next Pytorch (v2.1) release? so that we can plan the dependent features accordingly. Thank you!

**Comment by snadampal** [comment]
can someone please share some details on which oneDNN is targeted for PyTorch 2.1 upcoming release?

**Comment by Xia-Weiwen** [comment]
Hi @snadampal . We plan to update oneDNN in next PyTorch release. It's still under progress.

**Comment by snadampal** [comment]
Thanks @Xia-Weiwen ! Is it going to be oneDNN3.2? or oneDNN3.1?

**Comment by Xia-Weiwen** [comment]
> Thanks @Xia-Weiwen ! Is it going to be oneDNN3.2? or oneDNN3.1?

It will be oneDNN 3.1.

**Comment by snadampal** [comment]
Thank you! is there a ideep branch with oneDNN3.1 that we can use for the validation?
