### ISSUE TITLE
Any particular reason why IDEEP requires g++>5.3? 

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#2]
Recently https://github.com/pytorch/pytorch/pull/6699 has brought IDEEP into Pytorch. But our gcc requirement is not that tight. In fact, I built with g++4.8 and it seems to build and runs OK. Hence the question here.

**Comment by 4pao** [comment]
@yinghai The integration of ideep into pytorch had no requirement of g++ version over 5.3. The requirement is for test infrastructure, especially rapid-check. I'll make that clear in README.

**Comment by 4pao** [comment]
Err... I don't see that. Will change it.
