### ISSUE TITLE
Wheels should not depend on libpythonX.Y.so.1

### ISSUE THREAD

**Issue by kmaehashi** [intel/ideep#22]
Currently iDeep wheels provided on PyPI depends on `libpythonX.Y.so.1`.
This violates the manylinux1 rule. https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1
Moreover, it cannot be run in some environment.

> Furthermore, explicit linking to libpython creates problems in the common configuration where Python is not built with --enable-shared. In particular, on Debian and Ubuntu systems, apt install pythonX.Y does not even install libpythonX.Y.so.1, meaning that any wheel that did depend on libpythonX.Y.so.1 could fail to import.

**Comment by mingxiaoh** [comment]
@kmaehashi I remember that option "--enable-shared" will affect the unicode. 
did you pip install the package from web directly or download the package to local first and then install it? For python2.7,  ideep4py-1.0.4-cp27-cp27m-manylinux1_x86_64.whl and ideep4py-1.0.4-cp27-cp27mu-manylinux1_x86_64.whl are for different unicode, it will pick proper package if you pip install package from web directly. As for the question that whether we can remove the dependence on libpythonx-y-so-1, we need some time to check it further before give you feedback. Thanks.

**Comment by mingxiaoh** [comment]
@kmaehashi We have figured out the problem now, we will make new PYPI packages not depend on  libpythonX.Y.so. The new PYPI packages are under full validation test now, we will upload them and inform you once it is done. Thanks.

**Comment by kmaehashi** [comment]
Thank you for the prompt action!

**Comment by mingxiaoh** [comment]
@kmaehashi we have uploaded new ideep4py packages to PYPI  hub, you can install it by "pip install ideep4py" or "pip install ideep4py==2.0.0.post2". Thanks.

**Comment by kmaehashi** [comment]
Thanks for the prompt action! I confirmed that the `post2` build no longer depends on libpython.

However, after running the command `pip install ideep4py==2.0.0.post2`, the installed package version is displayed as `2.0.0` instead of `2.0.0.post2`.

```
$ pip install ideep4py==2.0.0.post2
Collecting ideep4py
  Using cached https://files.pythonhosted.org/packages/42/69/b5d1e7270fc6ec717c3f6c37ba38b3e7b1a9c1cf86907f37f315914da0c0/ideep4py-2.0.0.post2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: ideep4py
  Found existing installation: ideep4py 2.0.0
    Uninstalling ideep4py-2.0.0:
      Successfully uninstalled ideep4py-2.0.0
Successfully installed ideep4py-2.0.0
$ pip freeze | grep ideep4py
ideep4py==2.0.0
```

So, when I run `pip install -U`, pip tries to update to v2.0.0.post2 even if I have already installed it (because `2.0.0.post2` is newer than `2.0.0`).

```
$ pip install -U ideep4py
Collecting ideep4py
  Using cached https://files.pythonhosted.org/packages/42/69/b5d1e7270fc6ec717c3f6c37ba38b3e7b1a9c1cf86907f37f315914da0c0/ideep4py-2.0.0.post2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: ideep4py
  Found existing installation: ideep4py 2.0.0
    Uninstalling ideep4py-2.0.0:
      Successfully uninstalled ideep4py-2.0.0
Successfully installed ideep4py-2.0.0

$ pip install -U ideep4py
Collecting ideep4py
  Using cached https://files.pythonhosted.org/packages/42/69/b5d1e7270fc6ec717c3f6c37ba38b3e7b1a9c1cf86907f37f315914da0c0/ideep4py-2.0.0.post2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: ideep4py
  Found existing installation: ideep4py 2.0.0
    Uninstalling ideep4py-2.0.0:
      Successfully uninstalled ideep4py-2.0.0
Successfully installed ideep4py-2.0.0
```

Please note that generally you shouldn't rename the built wheel file.

 I think this is an trivial issue and no immediate action is required for now. Please consider fixing this issue in upcoming releases.

**Comment by mingxiaoh** [comment]
@kmaehashi Yes, I noticed this issue, I rename the internal version file as 2.0.0.post1 when building 2.0.0.post1 wheel. However, I suddenly notice that there is no need to do so, that is why I keep the internal version as 2.0.0 when building 2.0.0.post2 this time. As for reason why I renamed the external built wheel file, it is because we cannot upload same version wheels on PYPI, neither can we delete them.

**Comment by kmaehashi** [comment]
> However, I suddenly notice that there is no need to do so, that is why I keep the internal version as 2.0.0 when building 2.0.0.post2 this time.

I think it is not general convention to treat 2.0.0.post2 as 2.0.0 releases.
https://pypi.org/project/ideep4py/2.0.0/#files
e.g., protobuf: https://pypi.org/project/protobuf/3.5.2.post1/#history

**Comment by mingxiaoh** [comment]
@kmaehashi , thanks for the info. If so, we will update the packages soon(no later than tomorrow).

**Comment by kmaehashi** [comment]
Thank you!

**Comment by mingxiaoh** [comment]
@kmaehashi new(2.0.0.post3) ideep4py packages have been uploaded to PYPI hub. Thanks.
