### ISSUE TITLE
Update MKL-DNN submodule

### ISSUE THREAD

**Issue by kleisauke** [intel/ideep#23]
When building PyTorch from source with the `-DUSE_MKL=ON` and `-DUSE_IDEEP=ON` flags, the compilation of MKL-DNN fails with GCC 8 because the submodule version of MKL-DNN is too old.

A bugfix for MKL-DNN was made recently (see intel/mkl-dnn#283) and should solve the issue. For now, this issue can be resolved when building with the `-DCMAKE_CXX_FLAGS=-Wno-format-truncation` flag.

**Comment by mingxiaoh** [comment]
thanks for the notification, we will try and see.

**Comment by happydig** [comment]
any progress on this?

**Comment by gujinghui** [comment]
on track. will update here if any.

**Comment by mingxiaoh** [comment]
mkl-dnn works as an submodule in this repo, however its latest version depends on global cmake variables, such as CMAKE_SOURCE_DIR, CMAKE_BINARY_DIR, which will lead to building error for ideep, we are contacting with mkl-dnn team for the solution now.

**Comment by mingxiaoh** [comment]
grad to tell you that I was told by mkl-dnn team that they will fix the global cmake variables dependency problem on v0.17, so hopefully we can update mkl-dnn version in one or two weeks. sorry for keeping you waiting.

**Comment by mingxiaoh** [comment]
mkl-dnn team won't include the fix on v0.17, but they will push the fix to github master in 1 week, so we will update mkl-dnn version once we got the fix and finish the corresponding test. sorry for keeping you waiting.

**Comment by kleisauke** [comment]
I just came across PR https://github.com/pytorch/pytorch/pull/14308, thanks!

**Comment by kleisauke** [comment]
The above PR has been merged. :tada: 

I noticed that the submodule URL of MKL-DNN is still on `https://github.com/01org/mkl-dnn.git` instead than `https://github.com/intel/mkl-dnn.git` (see [here](https://github.com/intel/ideep/blob/d06f361c530dda79f49192953b2e896861e84602/.gitmodules#L3)). Perhaps the URL also needs to be updated?

**Comment by mingxiaoh** [comment]
that PR has been merged to master on https://github.com/01org/mkl-dnn.git, however, during our release test, we found that there is another issue we need to fix. Anyway, we plan to update submodule  of MKL-DNN this Friday.

**Comment by gujinghui** [comment]
> The above PR has been merged. 🎉
> 
> I noticed that the submodule URL of MKL-DNN is still on `https://github.com/01org/mkl-dnn.git` instead than `https://github.com/intel/mkl-dnn.git` (see [here](https://github.com/intel/ideep/blob/d06f361c530dda79f49192953b2e896861e84602/.gitmodules#L3)). Perhaps the URL also needs to be updated?

Sure. Will fix the URL.

**Comment by mingxiaoh** [comment]
@kleisauke we have updated ideep(and mkldnn version) in master branch, which includes the fix for GCC-8 compilation problem. we did not update mkldnn to latest version since there is some bugs we need to handle. Thanks.
