### ISSUE TITLE
How to install ideep4py on Windows?

### ISSUE THREAD

**Issue by coffeorange** [intel/ideep#26]
I cannot install ideep4py on Windows.

Is it possible to install ideep4py on Windows?
If is it possible, could you tell me how to install ideep4py on Windows?
Intel MKL is already in windows.

Can you give me advice?

**Comment by mingxiaoh** [comment]
sorry that ideep4py doesn't support installation on windows now, we have such a plan for it, but it should need some time.

**Comment by coffeorange** [comment]
OK, thanks.
I'm looking forward to using ideep4py on Windows.
I'll close this question.

**Comment by mingxiaoh** [comment]
@coffeorange Sorry for keeping you waiting, but would you mind tell us why you would like to install ideep4py on windows considering that installation on linux is much more convenient? Is it for business requirement or it just for personal research interest?
