### ISSUE TITLE
Let user use system installed mkl-dnn, googltest, rapidcheck ?

### ISSUE THREAD

**Issue by jiapei100** [intel/ideep#27]
I seriously do NOT wanna use the third-party submodules. Is it possible to let CMakeLists.txt to search for my local installed packages?

Thank you

**Comment by mingxiaoh** [comment]
@jiapei100 It is possible, but, the version of system installed mkl-dnn may be incompatible with current version of ideep(Chainer Backend for Intel Architecture).
