### ISSUE TITLE
Issue with `to_bytes(const int)` 

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#3]
Hey folks, I'm looking at this line: 
https://github.com/intel/ideep/blob/fb1adc449de61b56e92f8a81e02b91c068209f47/include/ideep/lru_cache.hpp#L425

Looks like it's trying to squeeze out the leading 0 bits. But I don't understand that next line is 
```
bytestring(as_cstring, len);
```
where address to `as_cstring` starts with zeros. Can someone help me understand what it is doing? Thanks. 

And BTW, `__builtin_clz(0)` is undefined behavior... 
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

**Comment by 4pao** [comment]
It is trying to find where to cut integer zeros, left only meaningful contents. And you are right, __builtin_clz is undefined when inputs is zero, a little dangerous to rely on compiler to generate safe pattern of 'bsr'.

**Comment by yinghai** [comment]
If it's trying to cutting off the leading zeros, `as_string` should be shifted to skip those zeros, right? 

On the other hand, why don't we just use 
```
byte_string(as_string, sizeof(int));
```
Any particular concerns?

**Comment by 4pao** [comment]
Well, the scenario we are dealing with is to create a key as short as possible, or we get a very long key when all sort of shapes stack up later. And we are trying to make it a little faster. The bug of __builtin_clz might degenerate performance by creating huge keys, that's a good catch.

**Comment by yinghai** [comment]
Yeah, you are right. I knew it was doing bit packing but got confused by the msb/lsb order. Now it all makes sense. 

About shape stacking, is this something you have benchmarked? Just curious. Because packing bit and now handle special value 0 will add logic too. Just wanted to see if the trade-off on hashing a shorter string is worth it and shows on profiling. 

If we do want to pack bits, maybe for 0 we can just return a string with 1 '/0'.

**Comment by 4pao** [comment]
Oh, we pack in byte granularity, For most of the case, we get 1/4 length of key, around 30 bytes. If we don't, we get over 120 bytes. We haven't benchmark it yet, just changed it from an very sloppy implementation that using std::to_string. If it manifests considerable performance penalty when profiling, we'll lift it to a more optimized implementation.

**Comment by yinghai** [comment]
Hi @4pao, when can we get the fix? Currently, your unit tests will actually hit this error. And I'm a bit blocked by it now. :)

**Comment by 4pao** [comment]
@yinghai The fix is ready. We are on a short vacation during 5/1, you know. I can only find person to push it to GitHub tomorrow. Sorry for the delay.

**Comment by yinghai** [comment]
Fixed in the master.
