### ISSUE TITLE
Question: interoperability with TBB

### ISSUE THREAD

**Issue by ilia-cher** [intel/ideep#30]
Hi, we're using TBB in our project, in particular we're using MKL-DNN library compiled with TBB instead of OpenMP. I noticed there's explicit usage of OMP though pragmas in ideep source files, what are the implications of using TBB version of MKL-DNN with ideep?

**Comment by CaoZhongZ** [comment]
We noticed that. We have plan to substitute all the OMP pragmas with portable wrappers.

**Comment by ilia-cher** [comment]
I see, thanks, that would be great!
