### ISSUE TITLE
Make the Windows build functional

### ISSUE THREAD

**Issue by peterjc123** [intel/ideep#35]
Hi! I tried to compile ideep with MSVC, but met the following kinds of issues:

1. symbol annotation : __attribute__((visibility("default"))) -> __dllspec(dllexport) / __dllspec(dllimport)
2. unsupported OpenMP clauses: #ifndef _MSC_VER
3. unsupported C99 VLA in MSVC: int a[c]; -> int* a = new int[c];
4. inline assembly code

I'm able to resolve the first three kinds of issues but then blocked by the last one because I have little knowledge about assembly code. I really think that you should support ideep on Windows because it is heavily used in deep learning libraries like PyTorch [1] and so on. Without that support, even if MKLDNN itself is supported on Windows, we could not use them actually in those frameworks. Doesn't that sound a little bit weird? What's more, the work won't take too much time because I was able to solve issue kind 1-3 in only 3-4 hrs.

References:
[1] https://github.com/pytorch/pytorch/issues/15982

**Comment by CaoZhongZ** [comment]
Thank you for your feedback. I have a question, do you use python part of iDeep?

**Comment by peterjc123** [comment]
No, I only use the C++ part.

**Comment by CaoZhongZ** [comment]
@XiaobingSuper will follow up.

**Comment by peterjc123** [comment]
@CaoZhongZ Thanks for your rapid response.

**Comment by CaoZhongZ** [comment]
Copying extension caffe2.python.caffe2_pybind11_state
Copying caffe2.python.caffe2_pybind11_state from torch\Lib\site-packages\caffe2\python\caffe2_pybind11_state.cp37-win_amd64.pyd to C:\Users\user\pytorch\build\lib.win-amd64-3.7\caffe2\python\caffe2_pybind11_state.cp37-win_amd64.pyd
building 'torch._C' extension
C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pytorch\Scripts\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\pytorch\include -IC:\Users\user\AppData\Local\Continuum\anaconda3\envs\pytorch\include /EHsc /Tptorch/csrc/stub.cpp /Fobuild\temp.win-amd64-3.7\Release\torch/csrc/stub.obj /MD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275
Usage: cl [options]
 
cl: error: no such option: -I
error: command 'C:\\Users\\user\\AppData\\Local\\Continuum\\anaconda3\\envs\\pytorch\\Scripts\\cl.exe' failed with exit status 2
 

Compile frameworks on Windows is relatively painful, did you meet these problems? @peterjc123 🤦‍♂️

**Comment by peterjc123** [comment]
What is 'C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pytorch\Scripts\cl.exe'? How did you install VS?

**Comment by XiaobingSuper** [comment]
This happend when I set **USE_NINJA=OFF**, an then 
```
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_TOOLSET_VERSION=14.11
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%
python setup.py install
```
but meet "command ```cl.exe failed```, so I install "clx" according to https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed:
```
cd [Visual Studio Path]\VC\Auxiliary\Build
.\vcvars32.bat
pip install cl
```
then meet this error.

**Comment by peterjc123** [comment]
No need to do this, please remove that and rerun the following script:
```cmd
set CMAKE_GENERATOR=Visual Studio 16 2019
set DISTUTILS_USE_SDK=1
for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16^,17^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64
python setup.py install --cmake
```

**Comment by XiaobingSuper** [comment]
@peterjc123, thanks, let me try.

**Comment by XiaobingSuper** [comment]
@peterjc123, I met the following compile error when I built pytorch:
```
C:\Users\xiaobin1\pytorch\caffe2/ideep/operators/operator_fallback_ideep.h(188): error C2201: 'const caffe2::IDEEPFallbackOp<caffe2::fb::`anonymous namespace'::CreateMutexOp,caffe2::SkipIndices<0> >::`vftable'': must have external linkage in order to be exported/imported
C:\Users\xiaobin1\pytorch\c10/util/Registry.h(184): note: see reference to class template instantiation 'caffe2::IDEEPFallbackOp<caffe2::fb::`anonymous-namespace'::CreateMutexOp,caffe2::SkipIndices<0>>' being compiled
..\caffe2\operators\atomic_ops.cc(97): note: see reference to function template instantiation 'ObjectPtrType c10::Registerer<std::string,ObjectPtrType,const caffe2::OperatorDef &,caffe2::Workspace *>::DefaultCreator<caffe2::IDEEPFallbackOp<caffe2::fb::`anonymous-namespace'::CreateMutexOp,caffe2::SkipIndices<0>>>(const caffe2::OperatorDef &,caffe2::Workspace *)' being compiled
        with
        [
            ObjectPtrType=std::unique_ptr<caffe2::OperatorBase,std::default_delete<caffe2::OperatorBase>>
        ]
..\caffe2\operators\atomic_ops.cc(97): note: see reference to function template instantiation 'ObjectPtrType c10::Registerer<std::string,ObjectPtrType,const caffe2::OperatorDef &,caffe2::Workspace *>::DefaultCreator<caffe2::IDEEPFallbackOp<caffe2::fb::`anonymous-namespace'::CreateMutexOp,caffe2::SkipIndices<0>>>(const caffe2::OperatorDef &,caffe2::Workspace *)' being compiled
        with
        [
            ObjectPtrType=std::unique_ptr<caffe2::OperatorBase,std::default_delete<caffe2::OperatorBase>>
        ]
```
to solve this problem, I commented the following code：
```
diff --git a/caffe2/operators/atomic_ops.cc b/caffe2/operators/atomic_ops.cc
index 313794f34d..9f2af7e38a 100644
--- a/caffe2/operators/atomic_ops.cc
+++ b/caffe2/operators/atomic_ops.cc
@@ -10,7 +10,7 @@

 namespace caffe2 {
 namespace fb {
-namespace {
+// namespace {

 class CreateMutexOp final : public Operator<CPUContext> {
  public:
@@ -150,6 +150,6 @@ SHOULD_NOT_DO_GRADIENT(AtomicFetchAdd);
 SHOULD_NOT_DO_GRADIENT(CreateAtomicBool);
 SHOULD_NOT_DO_GRADIENT(ConditionalSetAtomicBool);
 SHOULD_NOT_DO_GRADIENT(CheckAtomicBool);
-}
+//}
 }
 }
```
after that,  the compile error was gone, but has a link error:
```
FAILED: bin/torch_cpu.dll lib/torch_cpu.lib
cmd.exe /C "cd . && C:\Users\xiaobin1\AppData\Local\Continuum\anaconda3\envs\pytorch\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cpu.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe" /nologo @CMakeFiles\torch_cpu.rsp  /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO   && cd ."
LINK: command "C:\PROGRA~2\Microsoft Visual Studio\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cpu.rsp /out:bin\torch_cpu.dll /implib:lib\torch_cpu.lib /pdb:bin\torch_cpu.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cpu.dll.manifest" failed (exit code 1120) with the following output:
   Creating library lib\torch_cpu.lib and object lib\torch_cpu.exp
concat_split_op.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl caffe2::IDEEPFallbackOp<class caffe2::ConcatOp<class caffe2::CPUContext>,class caffe2::SkipIndices<0> >::IDEEPFallbackOp<class caffe2::ConcatOp<class caffe2::CPUContext>,class caffe2::SkipIndices<0> >(class caffe2::OperatorDef const &,class caffe2::Workspace *)" (__imp_??0?$IDEEPFallbackOp@V?$ConcatOp@VCPUContext@caffe2@@@caffe2@@V?$SkipIndices@$0A@@2@@caffe2@@QEAA@AEBVOperatorDef@1@PEAVWorkspace@1@@Z) referenced in function "public: __cdecl `anonymous namespace'::IDEEPConcatOp::IDEEPConcatOp(class caffe2::OperatorDef const &,class caffe2::Workspace *)" (??0IDEEPConcatOp@?A0xf52c31bf@@QEAA@AEBVOperatorDef@caffe2@@PEAVWorkspace@3@@Z)
concat_split_op.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl caffe2::IDEEPFallbackOp<class caffe2::ConcatOp<class caffe2::CPUContext>,class caffe2::SkipIndices<0> >::~IDEEPFallbackOp<class caffe2::ConcatOp<class caffe2::CPUContext>,class caffe2::SkipIndices<0> >(void)" (__imp_??1?$IDEEPFallbackOp@V?$ConcatOp@VCPUContext@caffe2@@@caffe2@@V?$SkipIndices@$0A@@2@@caffe2@@UEAA@XZ) referenced in function "int `public: __cdecl `anonymous namespace'::IDEEPConcatOp::IDEEPConcatOp(class caffe2::OperatorDef const &,class OperatorDef::Workspace *)'::`1'::dtor$1" (?dtor$1@?0???0IDEEPConcatOp@?A0xf52c31bf@@QEAA@AEBVOperatorDef@caffe2@@PEAVWorkspace@3@@Z@4HA)
```
Do you have any suggestion?

**Comment by peterjc123** [comment]
Would you please try the following steps:
1. Change the annotation of the class `IDEEPFallbackOp` in `caffe2\ideep\operators\operator_fallback_ideep.h` to `CAFFE2_API`.
2. Marking the classes `IDEEPConcatOp` and `IDEEPSplitOp` in `caffe2\ideep\operators\concat_split_op.cc` as `CAFFE2_API`.

**Comment by XiaobingSuper** [comment]
@peterjc123, thanks, the following patch works for me, I will try your methods.
```
diff --git a/caffe2/ideep/operators/operator_fallback_ideep.h b/caffe2/ideep/ope
rators/operator_fallback_ideep.h
index a022cac42d..27ea02ed66 100644
--- a/caffe2/ideep/operators/operator_fallback_ideep.h
+++ b/caffe2/ideep/operators/operator_fallback_ideep.h
@@ -36,7 +36,7 @@ namespace caffe2 {
  *                            IDEEPFallbackOp<MyMagicOp, SkipIndices<0>>);
  */
 template <class CPUOp, typename SkipOutputCopy = SkipIndices<>>
-class C10_EXPORT IDEEPFallbackOp final : public IDEEPOperator {
+class IDEEPFallbackOp final : public IDEEPOperator {
  public:
   USE_IDEEP_DEF_ALIASES();
   USE_IDEEP_OPERATOR_FUNCTIONS();
```

**Comment by XiaobingSuper** [comment]
@peterjc123 , https://github.com/pytorch/pytorch/pull/31355 can works in my side, but it failed in pytorch CI test for this reason:
```
C:\Users\circleci\project\third_party\ideep\include\ideep\utils.hpp(197): error C2039: 'time': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\chrono(20): note: see declaration of 'std'
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28107 for x64
```
Is it VS issue?

**Comment by peterjc123** [comment]
Would you please add `#include <ctime>` in `ideep\include\ideep\utils.hpp`?

**Comment by CaoZhongZ** [comment]
https://github.com/intel/ideep/blob/93963e630badf3806c6ec5420ded4e0f2feb3a63/include/ideep/utils.hpp#L66-L73

@peterjc123 Sorry for the long wait.

Though the code is not polished at all, the strangest thing in the Windows build was that the address allocated by allocator was 4 bytes offset from the 'p' passed to the deleter. The placement new put object offset 4 bytes in the memory even made it unaligned. It crashed deallocator eventually.

Maybe there is something fundamentally wrong about this code snippet, we'll dig into it and get a proper fix.

**Comment by peterjc123** [comment]
@CaoZhongZ Is there a minimal reproducible code example? I tried `s_vector<int>` and `s_vector<long long>` but it worked fine. Which allocator is used here?

**Comment by CaoZhongZ** [comment]
The problem should be the VS adding extra integer before initializing the whole list. Like new T [4] would be something like: 4, obj, obj, obj, obj.

**Comment by CaoZhongZ** [comment]
It’s something a long time ago, like the Star Wars. VS still kept the tradition, how nice. 😁

**Comment by peterjc123** [comment]
Are you referring to the behaviour of the `std::allocator` and the default `new[]` operator? I don't think so because I cannot reproduce it with the `s_vector` class for `int/char/class/struct` types. Maybe you are referring to our implementation of THRefcountedMapAllocator [here](https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THAllocator.cpp#L419-L430)?

**Comment by CaoZhongZ** [comment]
`int main(int argc, char **argv) {`
  `s_vector<std::shared_ptr<int>> v;`
  `v.assign(42, std::make_shared<int>(argc));`
  `std::cout << "Hello World!\n";`
`}`
Not the behaviour of allocator, the behaviour of compiler. Visual Studio Community 2017 will trigger error of s_vector. It also described here: https://stackoverflow.com/questions/15254/can-placement-new-for-arrays-be-used-in-a-portable-way

**Comment by CaoZhongZ** [comment]
Finished
