### ISSUE TITLE
What's the relationship between IDEEP and MKLDNN

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#4]
Hi folks, 
I haven't dug very deep on either IDEEP or MKLDNN codebase yet. Just the high level question, what is the relationship between IDEEP and MKLDNN? If IDEEP just a wrapper around MKLDNN primitives to make writing DNN operators easier? Thanks.

**Comment by 4pao** [comment]
Yes. iDeep is a wrapper/bridge of MKL-DNN, which makes it easy to use for frameworks, also guarantee its efficiency.

**Comment by yinghai** [comment]
BTW, as a wrapper, do you guys know how much overhead does it add compared using raw mkldnn primitives directly?

**Comment by 4pao** [comment]
Minimum overhead is imposed by this wrapper. We build the wrapper on top of MKL-DNN C API instead of its C++ one, and take necessary steps only to guarantee maximum performance from MKL-DNN. We also commit to optimize frameworks on intel platform.
