### ISSUE TITLE
Recent force push means all submodule pointers broke

### ISSUE THREAD

**Issue by ezyang** [intel/ideep#6]
Recently ideep repository had a force push from https://github.com/pytorch/ideep/commit/fb1adc449de61b56e92f8a81e02b91c068209f47 to https://github.com/intel/ideep/commit/526cf8186936fa83580ea485e43ac512fffb9804

This generally makes downstream users grumpy because it means that their submodule pointers stop working with:

```
fatal: reference is not a tree: fb1adc449de61b56e92f8a81e02b91c068209f47
Unable to checkout 'fb1adc449de61b56e92f8a81e02b91c068209f47' in submodule path 
'third_party/ideep'
```

Generally, it's better to avoid force push. But if there is no other option, I'd recommend keeping the old commits around using a tag.

**Comment by 4pao** [comment]
Sorry for the clumsy, We'll push rich history out very soon.

**Comment by yinghai** [comment]
I think this issue can be closed as it is no longer the case.
