### ISSUE TITLE
How to use Conv+Sum+Relu fusion? 

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#8]
Hi, folks, 
I'm trying to make sense of this constraint for `ConvFusion` (`iattr::residue`) op:
https://github.com/pytorch/pytorch/blob/150af6ac1eaedf8aa2ca2a1ca9938bfb3d24d1c5/caffe2/ideep/operators/conv_fusion_op.cc#L144

Basically, what it means is that we need to overwrite the input `S` with output. How does this even work in inference? Because after one run, the value of my `S` has changed. And subsequent run will observe different weights. It doesn't look correct to me. Any thoughts? @4pao

**Comment by 4pao** [comment]
@gujinghui Jinghui can explain fusion op related question.

**Comment by yinghai** [comment]
OK. Looks like this is really only beneficial towards training:
https://github.com/intel/mkl-dnn/blob/b4137dfc88e3bf5c6b62e833121802eb8c6696da/include/mkldnn.h#L355-L363

**Comment by yinghai** [comment]
@gujinghui Any thoughts?

**Comment by gujinghui** [comment]
@yinghai 
The sum fusion works like below:
   Y1 = Conv(X, w, b)  then Y2 = Sum(S, Y1)  **---fused to--->**  S = Sum(S, Conv(X, w, b))
Yes, the S will be overwriten by this fusion.
So, any subsequent ops can not refer to the S in original model.
Or, they cannot be fused together.

**Comment by yinghai** [comment]
> Y1 = Conv(X, w, b) then Y2 = Sum(S, Y1) ---fused to---> S = Sum(S, Conv(X, w, b))

Yes, that's my understanding too, which makes it not useful in inference.

**Comment by yinghai** [comment]
I think we have converged in this issue.

**Comment by jgong5** [comment]
@yinghai It was designed for inference since for training it is possible that BN is after conv, making this fusion not useful. For inference, BN can be folded into conv.

**Comment by yinghai** [comment]
> For inference, BN can be folded into conv.

We for inference, BN can be statically folded into conv. In fact, we already do that in Caffe2. :) 
https://github.com/pytorch/pytorch/blob/ed3b12e1baeebda5fd87fd9aab913a9f24a805be/caffe2/python/ideep/transform_ideep_net.py#L97
