### ISSUE TITLE
Any possibility to implement ChannelShuffle op? 

### ISSUE THREAD

**Issue by yinghai** [intel/ideep#9]
Hi folks,
Shufflenet is a pretty popular model (https://arxiv.org/abs/1707.01083). And we tried to run in on IDEEP ops. The only thing that MKLDNN doesn't support is the ChannelShuffle primitive, so we ended up doing fallback to our our implementation and do the context switch. We noticed that MKLDNN's depthwise CNN really helps in this model but the performance is hampered by the context switch, which manifests as reordering of inputs at the conv op. Since channel shuffle is conceptually similar to reorder, is there any possibility that we can add support to that? Here is a reference implementation of ChannelShuffle just to get the idea of what it is: https://github.com/pytorch/pytorch/blob/master/caffe2/operators/channel_shuffle_op.h#L14-L64

Conceptually, you can think if as splitting the channel dimension (c) into two dimension g and k (c = g * k) and then transpose g and k and merge it back to c.

**Comment by jgong5** [comment]
@yinghai Is ShuffleNet heavily used in Facebook? A previous study from us showed that it is difficult for the community to reproduce their result and the effectiveness of channel shuffle to other typologies is also questionable. What is your take on this?

**Comment by yinghai** [comment]
It's useful.

**Comment by jgong5** [comment]
@yinghai OK. We will consider the optimization then.

**Comment by yinghai** [comment]
Awesome. How are you going to do about it? Just curious. One thing is that you need to know the expected input order of the conv op, right?

**Comment by jgong5** [comment]
@yinghai We once thought of the solution like adding a channel-shuffle post-op attribute to the convolution so that it directly stores the output to the correct channel offset. Let us discuss internally first.

**Comment by yinghai** [comment]
@jgong5 awwwwwwsome! I think post-op is a good direction to explore. Let me know if you guys have a plan. I can help contribute code too. :)

**Comment by mingxiaoh** [comment]
@yinghai  can I close the issue now?
